FROM php:8.1-fpm-alpine as php

LABEL Maintainer="Behnam Rasouli <bmrbehnam@gmail.com>"

RUN apk add --update linux-headers
RUN apk add --no-cache  \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libpq-dev  \
    oniguruma-dev \
    libzip-dev \
    zip \
    libxml2-dev \
    libsodium-dev \
    gmp-dev \
    vim \
    git

RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        -j$(nproc) gd \
        bcmath \
        mbstring \
        soap \
        sodium \
        zip \
        pdo \
        pdo_mysql \
        pdo_pgsql \
        pcntl \
        exif \
        gmp

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


COPY ./ /tmp/app
RUN chgrp -R 0 /tmp/app && \
    chmod -R g=u /tmp/app && \
    cp -a /tmp/app/. /var/www/html && \
    rm -rf /tmp/app


# Use deluser and adduser to modify UID and GID
RUN deluser www-data \
    && adduser -D -u 1000 -g 1000 www-data
# Switch to the www-data user
USER www-data

RUN pear config-set php_bin /usr/local/bin/php

WORKDIR /var/www/html

VOLUME ["/var/www/html"]
ENTRYPOINT ["/usr/local/sbin/php-fpm"]


FROM php:8-cli-alpine as php_worker

COPY --from=php /var/www/html /var/www/html

RUN echo "* * * * * php -d memory_limit=-1 /var/www/html/artisan schedule:run >> /dev/null 2>&1" | crontab -

FROM nginx:stable-alpine as nginx
COPY --from=php /var/www/html/public /var/www/html/public
RUN chown -R nginx. /var/cache/nginx/
COPY ./docker/dev/nginx/default.conf /etc/nginx/conf.d/default.conf
