version: "3.8"
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile.dev
            target: php
        container_name: ${APP_NAME}-php
        volumes:
            - ./:/var/www/html/
        networks:
            - site_network
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.dev
            target: nginx
        container_name: ${APP_NAME}-nginx
        ports:
            - "${APP_PORT}:80"
        networks:
            - site_network
        volumes:
            - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        container_name: ${APP_NAME}-mysql
        ports:
            - "3307:3306"
        restart: always
        volumes:
            - mysql8data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - site_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${APP_NAME}-phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - site_network
        ports:
            - "${PHPMYADMIN_PORT}:80"

#    redis:
#        image: redis:6-alpine
#        container_name: ${APP_NAME}-redis
#        ports:
#            - "6378:6379"
#        networks:
#            - site_network

networks:
    site_network:
        driver: bridge

volumes:
    mysql8data:
        driver: local
